### ISSUE TITLE
Can not load font

### ISSUE THREAD

**Issue by mrllking** [CodementorIO/nextjs-redux-starter#5]
I need to use font in my css for using icon
```css
@font-face {
  font-family: 'fontello';
  src: url('../fonts/fontello/fontello.eot?14833847');
  src: url('../fonts/fontello/fontello.eot?14833847#iefix') format('embedded-opentype'),
       url('../fonts/fontello/fontello.woff2?14833847') format('woff2'),
       url('../fonts/fontello/fontello.woff?14833847') format('woff'),
       url('../fonts/fontello/fontello.ttf?14833847') format('truetype'),
       url('../fonts/fontello/fontello.svg?14833847#fontello') format('svg');
  font-weight: normal;
  font-style: normal;
 }
```
But it's seem the font couldn't be loaded. Please help to check.
